# Generated by Django 3.1.4 on 2020-12-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rekening',
            fields=[
                ('kd_rek', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nm_rek', models.CharField(blank=True, max_length=100, null=True)),
                ('tipe', models.CharField(blank=True, max_length=1, null=True)),
                ('balance', models.CharField(blank=True, max_length=1, null=True)),
                ('level', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'rekening',
                'managed': True,
            },
        ),
    ]
