/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package templatesbuilder;

import java.awt.Dimension;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author guruhyes
 */
public class codeBuilder extends javax.swing.JFrame {

    /**
     * Creates new form codeBuilder
     */
    String code = new String();
    JLabel lblId = new JLabel("Id");
    JTextField txtId = new JTextField();
    JLabel lblTitle = new JLabel("Title");
    JTextField txtTitle = new JTextField();
    JLabel lblDataOptions = new JLabel("Data Options");
    JTextField txtDataOptions = new JTextField("iconCls:'icon-save',");
    JLabel lblWidth = new JLabel("Width");
    JTextField txtWidth = new JTextField("400px");
    JLabel lblHeight = new JLabel("Height");
    JTextField txtHeight = new JTextField("200px");

    public codeBuilder() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgCodeParameter = new javax.swing.JDialog();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taCode = new javax.swing.JTextArea();
        jBasicDialog = new javax.swing.JRadioButton();

        dlgCodeParameter.getContentPane().setLayout(new java.awt.FlowLayout());

        jButton1.setText("Generate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        dlgCodeParameter.getContentPane().add(jButton1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        taCode.setColumns(20);
        taCode.setRows(5);
        jScrollPane1.setViewportView(taCode);

        jBasicDialog.setText("Basic Dialog");
        jBasicDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBasicDialogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 841, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBasicDialog)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jBasicDialog)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBasicDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBasicDialogActionPerformed
        // TODO add your handling code here:
        if (jBasicDialog.isSelected()) {
            dlgCodeParameter.add(lblId);
            txtId.setPreferredSize(new Dimension(150, 30));
            dlgCodeParameter.add(txtId);
            dlgCodeParameter.add(lblTitle);
            txtTitle.setPreferredSize(new Dimension(150, 30));
            dlgCodeParameter.add(txtTitle);
            dlgCodeParameter.add(lblDataOptions);
            txtDataOptions.setPreferredSize(new Dimension(150, 30));
            dlgCodeParameter.add(txtDataOptions);
            dlgCodeParameter.add(lblHeight);
            txtHeight.setPreferredSize(new Dimension(150, 30));
            dlgCodeParameter.add(txtHeight);
            dlgCodeParameter.add(txtWidth);
            txtWidth.setPreferredSize(new Dimension(150, 30));
            dlgCodeParameter.add(txtWidth);
            dlgCodeParameter.setSize(700, 400);
            dlgCodeParameter.setVisible(true);
        }
    }//GEN-LAST:event_jBasicDialogActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (jBasicDialog.isSelected()) {
            code = "<div id=\""+txtId.getText()+"\" class=\"easyui-dialog\" title=\""+txtTitle.getText()+"\" data-options=\""+txtDataOptions.getText()+"\" style=\"width:"+txtWidth.getText()+";height:"+txtHeight.getText()+";\">\n"
                    + "\t The dialog content.\n"
                    + "</div>";
            taCode.setText(code);
            dlgCodeParameter.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(codeBuilder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(codeBuilder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(codeBuilder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(codeBuilder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new codeBuilder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog dlgCodeParameter;
    private javax.swing.JRadioButton jBasicDialog;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taCode;
    // End of variables declaration//GEN-END:variables
}
