# Generated by Django 3.1.4 on 2020-12-15 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agama', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='agama',
            new_name='data',
        ),
    ]
